"""Squad aging & 4-year uncertainty for the WC-2030 outlook.

Three measured effects (calibration in ml/artifacts/aging_calibration.json,
regenerated by scripts/calibrate_aging.py), applied to each team's rating
before the 2030 simulation:

1. RELATIVE AGING (deterministic, centered): a team carried by *old* scorers
   will lose more of its current attack by 2030 than one with a young core.
   For each contributor we read their birthdate (Wikidata CC0) -> age at the
   2030 finals -> probability of still scoring, from the survival curve.
   Team aging-loss = Σ share_i · (1 − P_survive_i). We subtract the field
   mean so only *relative* age structure moves ratings — the average team
   loses its aging stars to new players who are not modelled individually
   (you cannot name a 2030 breakout today), so the mean effect is zero by
   construction.

2. GENERAL UNCERTAINTY (stochastic): measured 4-year Elo residual std
   (~63 Elo, with persistence β≈1 → a random walk). Drawn per team per
   realization; this is the honest home of "unknown upcoming players" — it
   is variance, not a point estimate, so it flattens 2030 odds rather than
   pretending to know who emerges.

3. YOUTH TAILWIND (small, centered): teams whose recent scorers are young
   get a mild positive nudge (their core is likely to still be there and
   improving). Folded into (1) via the survival curve, kept mild and capped.

All effects are bounded and clearly labeled assumptions. Ratings 4 years out
are genuinely uncertain; this makes the outlook *humbler*, not more precise.
"""

from __future__ import annotations

import json
from datetime import date
from functools import lru_cache

import numpy as np
import polars as pl

from kickoff_ml.config import ARTIFACTS_DIR, PROCESSED_DIR

AGING_ELO_SCALE = 220.0   # maps centered attack-share loss -> Elo points
AGING_ELO_CAP = 130.0     # bound on the deterministic aging adjustment
FINALS_2030 = date(2030, 6, 1)

# Embedded fallback if the calibration artifact is absent (values measured
# 2026-07; see scripts/calibrate_aging.py).
_FALLBACK = {
    "elo_dynamics": {"residual_std": 63.0, "persistence_beta": 1.0},
    "scoring_survival": {
        "22": 0.53, "24": 0.43, "26": 0.32, "28": 0.22,
        "30": 0.14, "32": 0.08, "34": 0.045, "36": 0.056,
    },
}


@lru_cache(maxsize=1)
def _calibration() -> dict:
    path = ARTIFACTS_DIR / "aging_calibration.json"
    if path.exists():
        return json.loads(path.read_text())
    return _FALLBACK


def survival_prob(age_2030: float) -> float:
    """P(a scorer of this age at the 2030 finals is still scoring then),
    linearly interpolated over the measured survival knots."""
    knots = sorted((float(a), p) for a, p in _calibration()["scoring_survival"].items())
    if age_2030 <= knots[0][0]:
        return knots[0][1]
    if age_2030 >= knots[-1][0]:
        return max(knots[-1][1], 0.02)
    for (a0, p0), (a1, p1) in zip(knots[:-1], knots[1:], strict=True):
        if a0 <= age_2030 <= a1:
            t = (age_2030 - a0) / (a1 - a0)
            return p0 + t * (p1 - p0)
    return 0.05


def residual_std() -> float:
    return float(_calibration()["elo_dynamics"]["residual_std"])


@lru_cache(maxsize=1)
def _team_aging_loss() -> dict[str, float]:
    """team_id -> expected fraction of current recorded attack lost to aging
    by the 2030 finals (share-weighted survival shortfall)."""
    p = PROCESSED_DIR / "players.parquet"
    if not p.exists():
        return {}
    df = pl.read_parquet(p).filter(
        pl.col("recently_active") & pl.col("dob").is_not_null()
    )
    losses: dict[str, float] = {}
    weights: dict[str, float] = {}
    for r in df.iter_rows(named=True):
        try:
            born = date.fromisoformat(r["dob"])
        except (ValueError, TypeError):
            continue
        age = (FINALS_2030 - born).days / 365.25
        share = float(r["scenario_share"])
        losses[r["team_id"]] = losses.get(r["team_id"], 0.0) + share * (1.0 - survival_prob(age))
        weights[r["team_id"]] = weights.get(r["team_id"], 0.0) + share
    # normalize by covered share so teams with thin dob coverage aren't skewed
    return {t: losses[t] / weights[t] for t in losses if weights[t] > 0.15}


def relative_aging_elo(team_ids: list[str]) -> dict[str, float]:
    """Centered, bounded Elo adjustment per team from squad age structure.

    Only teams with enough dated contributors get a non-zero value; the
    adjustment is centered on the participating field's mean so the average
    team is unchanged (new players replace aging ones on average)."""
    loss = _team_aging_loss()
    present = {t: loss[t] for t in team_ids if t in loss}
    if not present:
        return {t: 0.0 for t in team_ids}
    field_mean = float(np.mean(list(present.values())))
    adj: dict[str, float] = {}
    for t in team_ids:
        if t in present:
            raw = -AGING_ELO_SCALE * (present[t] - field_mean)
            adj[t] = float(np.clip(raw, -AGING_ELO_CAP, AGING_ELO_CAP))
        else:
            adj[t] = 0.0  # no dated core -> no defensible aging signal
    return adj


def summary(team_ids: list[str]) -> dict:
    adj = relative_aging_elo(team_ids)
    ranked = sorted(adj.items(), key=lambda kv: kv[1])
    return {
        "residual_std_elo": round(residual_std(), 1),
        "aging_elo_scale": AGING_ELO_SCALE,
        "aging_elo_cap": AGING_ELO_CAP,
        "most_aged_teams": [{"team_id": t, "elo_delta": round(v, 1)} for t, v in ranked[:5]],
        "youngest_teams": [
            {"team_id": t, "elo_delta": round(v, 1)} for t, v in ranked[::-1][:5]
        ],
        "teams_with_age_signal": sum(1 for v in adj.values() if abs(v) > 0.5),
    }
