"""Inject actual evaluation-artifact metrics into README.md.

The README never contains hand-typed metrics: everything between the
<!-- METRICS:START --> / <!-- METRICS:END --> markers is generated here.
Run after `make evaluate`.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

metrics = json.loads((ROOT / "ml/artifacts/metrics.json").read_text())
comparison = json.loads((ROOT / "ml/artifacts/model_comparison.json").read_text())
quality = json.loads((ROOT / "data/manifests/data_quality.json").read_text())
tuning = json.loads((ROOT / "ml/artifacts/elo_tuning.json").read_text())

order = [
    "frequency_baseline", "elo_logistic", "poisson", "dixon_coles",
    "gbm_uncalibrated", "gbm_calibrated", "geometric_ensemble",
]
order = [n for n in order if n in comparison]
rows = []
for name in order:
    v, t = comparison[name]["validation"], comparison[name]["test"]
    star = " ⭐" if name == metrics["champion"] else ""
    rows.append(
        f"| {name}{star} | {v['log_loss']:.4f} | {t['log_loss']:.4f} "
        f"| {t['rps']:.4f} | {t['accuracy']:.1%} | {t['ece']:.4f} |"
    )

ct = metrics["champion_test"]
block = f"""<!-- METRICS:START (generated by scripts/update_readme_metrics.py — do not edit) -->
**Data:** {quality["completed_matches"]:,} completed internationals ({quality["date_min"]} → {quality["date_max"]}),
{quality["upcoming_fixtures"]} upcoming fixtures, {quality["goal_events_kept"]:,} goal events · model `{metrics["model_version"]}`

**Protocol:** fit {metrics["protocol"]["fit_window"][0]} → {metrics["protocol"]["fit_window"][1]}
({metrics["counts"]["train"]:,} matches) · validation {metrics["protocol"]["validation_window"][0]} → {metrics["protocol"]["validation_window"][1]}
({metrics["counts"]["validation"]:,}) · untouched test {metrics["protocol"]["test_window"][0]} → {metrics["protocol"]["test_window"][1]}
({metrics["counts"]["test"]:,}) · champion selected fully out-of-sample on validation · Elo tuned to
home_advantage={tuning["selected"]["home_advantage"]:.0f}, k_scale={tuning["selected"]["k_scale"]}

| Model | Val log loss | Test log loss | Test RPS | Test acc. | Test ECE |
|---|---|---|---|---|---|
{chr(10).join(rows)}

**Champion (`{metrics["champion"]}`) on untouched test (n={ct["n"]:,}):** log loss
**{ct["log_loss"]:.4f}**, RPS **{ct["rps"]:.4f}**, Brier {ct["brier"]:.4f}, top-pick
accuracy **{ct["accuracy"]:.1%}**, ECE **{ct["ece"]:.4f}** — best on both validation and test.
Honest note: a *learned* stack and the isotonic-calibrated GBM overfit this modest data and
lose under rigorous out-of-sample selection; the parameter-free geometric mean generalizes.
<!-- METRICS:END -->"""

readme = ROOT / "README.md"
text = readme.read_text() if readme.exists() else ""
if "<!-- METRICS:START" in text:
    text = re.sub(
        r"<!-- METRICS:START.*?<!-- METRICS:END -->", block, text, flags=re.S
    )
    readme.write_text(text)
    print("README metrics refreshed")
else:
    print(block)
